const employees = [
    { firstName: "John", lastName: "Doe", department: "HR", dateOfBirth: "1990-05-15", street: "123 Main St", city: "New York", zipCode: "10001", state: "NY" },
    { firstName: "Jane", lastName: "Smith", department: "Engineering", dateOfBirth: "1985-07-20", street: "456 Elm St", city: "Los Angeles", zipCode: "90001", state: "CA" },
    { firstName: "Alice", lastName: "Johnson", department: "Marketing", dateOfBirth: "1992-03-10", street: "789 Oak St", city: "Chicago", zipCode: "60601", state: "IL" },
    { firstName: "Bob", lastName: "Brown", department: "Sales", dateOfBirth: "1988-11-25", street: "321 Pine St", city: "Houston", zipCode: "77001", state: "TX" },
    { firstName: "Charlie", lastName: "Davis", department: "HR", dateOfBirth: "1995-01-30", street: "654 Maple St", city: "Phoenix", zipCode: "85001", state: "AZ" },
    { firstName: "Emily", lastName: "Clark", department: "Engineering", dateOfBirth: "1993-09-12", street: "987 Cedar St", city: "Philadelphia", zipCode: "19101", state: "PA" },
    { firstName: "Frank", lastName: "Miller", department: "Marketing", dateOfBirth: "1987-06-18", street: "159 Birch St", city: "San Antonio", zipCode: "78201", state: "TX" },
    { firstName: "Grace", lastName: "Wilson", department: "Sales", dateOfBirth: "1991-12-05", street: "753 Walnut St", city: "San Diego", zipCode: "92101", state: "CA" },
    { firstName: "Hank", lastName: "Taylor", department: "HR", dateOfBirth: "1989-04-22", street: "852 Spruce St", city: "Dallas", zipCode: "75201", state: "TX" },
    { firstName: "Ivy", lastName: "Anderson", department: "Engineering", dateOfBirth: "1994-08-15", street: "951 Chestnut St", city: "San Jose", zipCode: "95101", state: "CA" },
    { firstName: "Jack", lastName: "White", department: "Marketing", dateOfBirth: "1990-02-28", street: "147 Poplar St", city: "Austin", zipCode: "73301", state: "TX" },
    { firstName: "Karen", lastName: "Green", department: "Sales", dateOfBirth: "1986-10-10", street: "369 Willow St", city: "Jacksonville", zipCode: "32099", state: "FL" },
    { firstName: "Liam", lastName: "Scott", department: "HR", dateOfBirth: "1992-07-07", street: "258 Cypress St", city: "Fort Worth", zipCode: "76101", state: "TX" },
    { firstName: "Mia", lastName: "Adams", department: "Engineering", dateOfBirth: "1988-03-03", street: "369 Redwood St", city: "Columbus", zipCode: "43085", state: "OH" },
    { firstName: "Noah", lastName: "Evans", department: "Marketing", dateOfBirth: "1995-11-11", street: "147 Aspen St", city: "Charlotte", zipCode: "28201", state: "NC" },
    { firstName: "Olivia", lastName: "Brown", department: "Sales", dateOfBirth: "1993-05-05", street: "753 Magnolia St", city: "San Francisco", zipCode: "94101", state: "CA" },
    { firstName: "Paul", lastName: "Walker", department: "HR", dateOfBirth: "1987-09-09", street: "951 Dogwood St", city: "Indianapolis", zipCode: "46201", state: "IN" },
    { firstName: "Quinn", lastName: "Hall", department: "Engineering", dateOfBirth: "1991-01-01", street: "123 Fir St", city: "Seattle", zipCode: "98101", state: "WA" },
    { firstName: "Rachel", lastName: "King", department: "Marketing", dateOfBirth: "1989-06-06", street: "456 Palm St", city: "Denver", zipCode: "80201", state: "CO" },
    { firstName: "Sam", lastName: "Lee", department: "Sales", dateOfBirth: "1994-12-12", street: "789 Hickory St", city: "Boston", zipCode: "02101", state: "MA" },
];